=== AkasLiu/com.novaframework.unity.core.common/Editor Default Resources/Config/repo_manifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- 类型定义 -->

    <xs:complexType name="environment-variable-type">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="asset-local-path-type">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="default-value" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="system-path-type">
        <xs:sequence>
            <xs:element name="local-path" type="asset-local-path-type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="package-local-assembly-type">
        <xs:sequence>
            <xs:element name="modularize-definition" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="loadable-strategy" type="assembly-loadable-strategy-type" minOccurs="1" maxOccurs="unbounded" nillable="false"/>
                    </xs:sequence>
                    <xs:attribute name="order" type="xs:integer" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="installable" type="xs:boolean"/>
        <xs:attribute name="configurable" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="package-import-strategy-type">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="installable" type="xs:boolean"/>
        <xs:attribute name="configurable" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="assembly-loadable-strategy-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Module"/>
            <xs:enumeration value="Game"/>
            <xs:enumeration value="Shared"/>
            <xs:enumeration value="Hotfix"/>
            <xs:enumeration value="Compile"/>
            <xs:enumeration value="Tutorial"/>
            <xs:enumeration value="Test"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="package-type">
        <xs:sequence>
            <xs:element name="git-repository">
                <xs:complexType>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="output-assemblies" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="local-assembly" type="package-local-assembly-type" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="installation-wizard" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="import-strategy" type="package-import-strategy-type" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="assembly-definition" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="loadable-strategy" type="assembly-loadable-strategy-type" minOccurs="1" maxOccurs="unbounded" nillable="false"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="order" type="xs:integer" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="asset-sources" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="local-path" type="asset-local-path-type" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="dependencies" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference-package" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="repulsions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference-package" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="pid" type="xs:integer" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="display-name" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>

    <!-- 元素定义 -->

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="environment-variable" type="environment-variable-type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="system-path" type="system-path-type" minOccurs="0" maxOccurs="1"/>
                <xs:element name="package" type="package-type" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AkasLiu/com.novaframework.unity.core.common/Editor Default Resources/Config/repo_manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repo_manifest.xsd">
    <!-- 环境参数设置 -->

    <environment-variable name="REPO_URL" value="https://github.com/yoseasoft"/>

    <system-path>
        <local-path name="ORIGINAL_RESOURCE_PATH" default-value="Assets/_Resources" title="原始资源目录" required="true"/>
        <local-path name="SOURCE_CODE_PATH" default-value="Assets/Sources" title="源码目录" required="true"/>
        <local-path name="SCRIPT_FILE_PATH" default-value="Assets/LuaScripts" title="脚本目录"/>
        <local-path name="AOT_LIBRARY_PATH" default-value="Assets/_Resources/Aot" title="预编译库目录" required="true"/>
        <local-path name="LINK_LIBRARY_PATH" default-value="Assets/_Resources/Code" title="链接库目录" required="true"/>
        <local-path name="CONTEXT_PATH" default-value="Assets/_Resources/Context" title="环境文件目录"/>
        <local-path name="CONFIG_PATH" default-value="Assets/_Resources/Config" title="配置文件目录"/>
        <local-path name="PROTOCOL_PATH" default-value="Assets/_Resources/Protocol" title="协议文件目录"/>
    </system-path>

    <!-- 插件包配置清单 -->

    <!-- 基础引擎库 -->
    <package pid="100011"
             name="com.novaframework.unity.core.common"
             display-name="NovaFramework.Common"
             title="Nova引擎核心通用库"
             required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.core.common.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Common"/>
            <local-assembly name="NovaEditor.Common"/>
        </output-assemblies>
    </package>
    <package pid="100012"
             name="com.novaframework.unity.core.configure"
             display-name="NovaFramework.Configure"
             title="Nova引擎核心配置库"
             required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.core.configure.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Configure" installable="true" configurable="true"/>
            <local-assembly name="NovaEditor.Configure"/>
        </output-assemblies>
        <installation-wizard>
            <import-strategy name="NovaEditor.Configure" installable="true" configurable="true"/>
        </installation-wizard>
        <dependencies>
            <reference-package>com.novaframework.unity.core.common</reference-package>
        </dependencies>
    </package>
    <package pid="100021"
             name="com.yoseasoft.gooasset"
             display-name="GooAsset"
             title="Goo资产管理框架"
             required="true">
        <git-repository url="%REPO_URL%/GooAsset.git"/>
        <output-assemblies>
            <local-assembly name="GooAsset"/>
            <local-assembly name="GooAsset.Editor" installable="true" configurable="true"/>
        </output-assemblies>
        <installation-wizard>
            <import-strategy name="GooAsset.Editor" installable="true" configurable="true"/>
        </installation-wizard>
    </package>
    <package pid="100031"
             name="com.yoseasoft.novaframework"
             display-name="NovaFramework"
             title="Nova引擎框架"
             required="true">
        <git-repository url="%REPO_URL%/NovaFramework.git"/>
        <output-assemblies>
            <local-assembly name="NovaEngine.Library"/>
            <local-assembly name="NovaEngine.Kernel"/>
            <local-assembly name="NovaEngine.Basic"/>
            <local-assembly name="NovaEngine.Import"/>
            <local-assembly name="NovaEngine.Editor"/>
        </output-assemblies>
        <dependencies>
            <reference-package>com.yoseasoft.gooasset</reference-package>
            <reference-package>com.novaframework.unity.core.configure</reference-package>
            <reference-package>com.novaframework.unity.unitask</reference-package>
        </dependencies>
    </package>
    <package pid="100041"
             name="com.novaframework.unity.core.boot"
             display-name="NovaFramework.Boot"
             title="Nova引擎核心启动库"
             required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.core.boot.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Boot"/>
            <local-assembly name="NovaEditor.Boot" installable="true"/>
        </output-assemblies>
        <installation-wizard>
            <import-strategy name="NovaEditor.Boot" installable="true"/>
        </installation-wizard>
        <dependencies>
            <reference-package>com.yoseasoft.gooasset</reference-package>
            <reference-package>com.novaframework.unity.core.common</reference-package>
            <reference-package>com.novaframework.unity.core.configure</reference-package>
            <reference-package>com.novaframework.unity.unitask</reference-package>
        </dependencies>
    </package>

    <!-- 第三方工具库 -->
    <package pid="100111"
             name="com.novaframework.unity.unitask"
             display-name="NovaFramework.UniTask"
             title="UniTask工具库"
             required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.unitask.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.UniTask"/>
            <local-assembly name="NovaEditor.UniTask"/>
        </output-assemblies>
    </package>
    <package pid="100112"
             name="com.novaframework.unity.litjson"
             display-name="NovaFramework.LitJson"
             title="LitJson工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.litjson.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.LitJson"/>
        </output-assemblies>
    </package>
    <package pid="100113"
             name="com.novaframework.unity.sharpziplib"
             display-name="NovaFramework.SharpZipLib"
             title="SharpZipLib工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.sharpziplib.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.SharpZipLib"/>
        </output-assemblies>
    </package>
    <package pid="100211"
             name="com.novaframework.unity.protobuf"
             display-name="NovaFramework.Protobuf"
             title="Protobuf工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.protobuf.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Protobuf"/>
            <local-assembly name="NovaFramework.Protobuf.Extension"/>
        </output-assemblies>
        <dependencies>
            <reference-package>com.novaframework.unity.litjson</reference-package>
        </dependencies>
        <repulsions>
            <reference-package>com.novaframework.unity.streambuf</reference-package>
        </repulsions>
    </package>
    <package pid="100212"
             name="com.novaframework.unity.streambuf"
             display-name="NovaFramework.Streambuf"
             title="Streambuf工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.streambuf.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Streambuf"/>
        </output-assemblies>
        <repulsions>
            <reference-package>com.novaframework.unity.protobuf</reference-package>
        </repulsions>
    </package>
    <package pid="100221"
             name="com.novaframework.unity.luban"
             display-name="NovaFramework.Luban"
             title="Luban工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.luban.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.Luban"/>
        </output-assemblies>
    </package>
    <package pid="100311"
             name="com.novaframework.unity.fairygui"
             display-name="NovaFramework.FairyGUI"
             title="FairyGUI工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.fairygui.git"/>
        <output-assemblies>
            <local-assembly name="NovaFramework.FairyGui"/>
            <local-assembly name="NovaEditor.FairyGui"/>
        </output-assemblies>
    </package>

    <!-- 游戏通用库 -->
    <package pid="101011"
             name="com.gameframework.unity.common"
             display-name="GameFramework.Common"
             title="Game通用库"
             description="针对Nova框架封装的部分通用接口及方法，用于业务层便捷使用">
        <git-repository url="%REPO_URL%/com.gameframework.unity.common.git"/>
        <output-assemblies>
            <local-assembly name="GameFramework.Common"/>
        </output-assemblies>
    </package>

    <!-- 游戏教程库 -->
    <package pid="101012"
             name="com.gameframework.unity.sample"
             display-name="GameFramework.Sample"
             title="Game教程库"
             description="针对Nova框架的特性以及调度方式，提供一些教程案例作为使用入门的参考">
        <git-repository url="%REPO_URL%/com.gameframework.unity.sample.git"/>
        <output-assemblies>
            <local-assembly name="GameFramework.Sample">
                <modularize-definition order="1">
                    <loadable-strategy>Module</loadable-strategy>
                    <loadable-strategy>Compile</loadable-strategy>
                    <loadable-strategy>Tutorial</loadable-strategy>
                </modularize-definition>
            </local-assembly>
            <local-assembly name="GameEdirot.Sample"/>
        </output-assemblies>
        <assembly-definition name="GameFramework.Sample" order="1">
            <loadable-strategy>Module</loadable-strategy>
            <loadable-strategy>Compile</loadable-strategy>
            <loadable-strategy>Tutorial</loadable-strategy>
        </assembly-definition>
        <dependencies>
            <reference-package>com.gameframework.unity.common</reference-package>
        </dependencies>
    </package>

    <!-- 游戏启动器 -->
    <package pid="101021"
             name="com.gameframework.unity.launcher"
             display-name="GameFramework.Launcher"
             title="Game启动模版"
